### ISSUE TITLE
Use a controlled vocabulary when linting input and output types in meta.yml

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/tools#1553]
### Description of feature

There are parts of the `meta.yml` that don't have a clear specification.
For example
```
input:
...
  - sdf:
      type: folder/file
      description: The SDF (RTG Sequence Data File) of the reference genome. Can be a folder or a tar-zipped folder.
      pattern: "*.{,tar.gz}"
```
input.sdf.type should probably use a controlled vocabulary, but it's currently uncontrolled.

It would be nice if 
`nf-core modules lint` validated the type using a controlled vocabulary.
