### ISSUE TITLE
Add new modules subcommand "update-meta-yml"

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/tools#1555]
### Description of feature

The meta.yml is currently updated manually, but the input and output fields could be auto-generated from the `main.nf` in the same directory.

For example
```nextflow
    input:
    tuple val(meta), path('tmp_input/*')
    each lineage                          
    path busco_lineages_path
    path config_file

    output:
    tuple val(meta), path("*-busco.batch_summary.txt"), emit: batch_summary
    tuple val(meta), path("short_summary.*.txt")      , emit: short_summaries_txt, optional: true
    tuple val(meta), path("short_summary.*.json")     , emit: short_summaries_json, optional: true
    tuple val(meta), path("*-busco")                  , emit: busco_dir
    path "versions.yml"                               , emit: versions

```
could be turned into output like:
```yaml
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - placeholder1: # TODO provide a suitable variable name for this placeholder 'tmp_input/*'
      type: file
      description: "# TODO add description"
  - lineage:
      type: string
      description: "# TODO add description"
  - busco_lineages_path:
      type: file
      description: "# TODO add description"
  - config_file:
      type: file
      description: "# TODO add description"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - batch_summary:
      type: file
      description: "# TODO add description"
      pattern: "*-busco.batch_summary.txt"
  - short_summaries_txt:
      type: file
      description: "# TODO add description"
      pattern: "short_summary.*.txt"
  - short_summaries_json:
      type: file
      description: "# TODO add description"
      pattern: "short_summary.*.json"
  - busco_dir:
      type: file
      description: "# TODO add description"
      pattern: "*-busco"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

```
