### ISSUE TITLE
Cancel CI tests if a new run is started

### ISSUE THREAD

**Issue by mirpedrol** [nf-core/tools#1758]
### Description of feature

As [suggested](https://nfcore.slack.com/archives/CE5LG7WMB/p1660829436819539) by @ewels, add the following lines to all CI tests. 
This code cancels a run if a new one starts right after.

```yaml
# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
```
