### ISSUE TITLE
Deploy docs using stages in travis

### ISSUE THREAD

**Issue by matq007** [nf-core/tools#182]
It would be super cool the support stages when running Travis like shown [here](https://travis-ci.com/nf-core/rnafusion/builds/87734776). Makes it nice and clean.
```yaml
# Example
stages:
  - lint
  - build
  - test
  # - unit-test

jobs:
  include:
      - stage: lint
        script: nf-core lint ${TRAVIS_BUILD_DIR}
      - stage: build
        script:
          - cd ${TRAVIS_BUILD_DIR}
          - sh build.sh
      - stage: test
        script: docker run -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} rnafusion-test nextflow run ${TRAVIS_BUILD_DIR} -profile test --reads "/test-data/test_{1,2}.fastq.gz" --genome R64-1-1 --star_fusion --test
      # - unit-test:
      #    script:
```
