### ISSUE TITLE
Indentation for module test.yml changed after v2.5.1 release

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1866]
### Description of the bug

Running `nf-core modules create-test-yml` the indentation has been removed whenever a line begins with `-`. 

## Old format

```yaml
- name: samtools index test_samtools_index_bai
  command: nextflow run ./tests/modules/nf-core/samtools/index -entry test_samtools_index_bai -c ./tests/config/nextflow.config -c ./tests/modules/nf-core/samtools/index/nextflow.config
  tags:
    - samtools
    - samtools/index
  files:
    - path: output/samtools/test.paired_end.sorted.bam.bai
      md5sum: 704c10dd1326482448ca3073fdebc2f4
```

## New format

```yaml
- name: samtools index test_samtools_index_bai
  command: nextflow run ./tests/modules/nf-core/samtools/index -entry test_samtools_index_bai -c ./tests/config/nextflow.config -c ./tests/modules/nf-core/samtools/index/nextflow.config
  tags:
  - samtools
  - samtools/index
  files:
  - path: output/samtools/test.paired_end.sorted.bam.bai
    md5sum: 704c10dd1326482448ca3073fdebc2f4
```
