### ISSUE TITLE
Add an option to make the new workflow name checks optional

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/tools#2117]
### Description of feature

When running `nf-core lint` on my pipeline it immediately fails with following error:
```
$ nf-core lint

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.7.1 - https://nf-co.re


INFO     Testing pipeline: .                                                                                                                                         
ERROR    Invalid workflow name: must be lowercase without punctuation. 
```

The pipeline name is something we agreed on for all our pipeline so I can't simply change it. So an option to disable this check would be helpful. Thanks in advance!!

**Comment by awgymer** [comment]
I thought we added code to skip this:

https://github.com/nf-core/tools/blob/eecf1c7079ef89e918a7493fb2228ac2fc63e5e0/nf_core/create.py#L170-L180

In theory if you have an `.nf-core.yml` with `manifest.name` specified to be skipped then this won't get triggered?
*BUT* I suppose we didn't think this through because how will you have one in a pipeline you are creating from scratch?

**Comment by nvnieuwk** [comment]
The `.nf-core.yml` config for the pipeline the command was run on looks like this: 
```yaml
repository_type: pipeline
lint:
  files_exist:
    - assets/nf-core-nfcmggstructural_logo_light.png
    - docs/images/nf-core-nfcmggstructural_logo_light.png
    - docs/images/nf-core-nfcmggstructural_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  readme:
    - nextflow_badge
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
    - .prettierignore
  actions_ci: false
```

Am I missing something?
