### ISSUE TITLE
New tool: Required publication references

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#236]
It would be nice to make it easier for people to know what should be referenced if they use a pipeline in a manuscript. For example, `nf-core references <pipeline-name>` could return a list of the references that you need to add into your paper. _(alt names: `nf-core refs`, `nf-core bib`..?)_

Different flags could give different output formats, but perhaps the default could be prose text. For example:

> _Data was processed using nf-core/rnaseq [pipeline DOI, nf-core paper]. This pipeline is built using nextflow [nextflow paper] and uses the following tools: FastQC (Quality control of raw data) [ref], TrimGalore! (Trimming of adapter sequence contamination) [ref], STAR (Alignment of RNA-seq reads to the reference genome) [ref]_ …etc

Need to think about where and how to capture this information in the pipeline files. For example, a simple YAML file could work nicely:

```yml
- tools:
    - fastqc:
        - name: FastQC
        - description: Quality control of raw data
        - ref: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
    - trimgalore:
        - name: Trim Galore!
        - description: Trimming of adapter sequence contamination
        - ref:
            - https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/
            - 10.14806/ej.17.1.200
    - star:
        - name: STAR
        - description: Alignment of RNA-seq reads to the reference genome
        - ref: 10.1093/bioinformatics/bts635
```

Requirements:
* Should handle either DOI or URL (DOI preferable where available)
* Should be able to handle multiple references per tool
    * Alternatively, force one per tool and instead list multiple tools? eg. have Cutadapt in its own entry above.
* Name and reference should be mandatory
* Additional text per tool should be as short as possible

Output options could be:
* List of references alone
* List of tool names and references
* Full prose text
* Prose text without additional tool descriptions
* Option to give references in different formats, with a DOI lookup

The nextflow and nf-core references can be hardcoded. The workflow DOI can be lifted from `README.md` I guess. Or could potentially be added as a new `workflow.metadata` variable?

Thoughts / feedback?

Phil
