### ISSUE TITLE
Add Markdown to lint option

### ISSUE THREAD

**Issue by matq007** [nf-core/tools#255]
I found this nice tool for linting markdown: [https://github.com/DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint). It would be nice to lint also the Markdown documentation.

**Comment by ewels** [comment]
Agreed, looks great! Maybe worth turning off some of the stricter rules (eg. I don't agree with `Multiple consecutive blank lines` being a problem), but could catch a lot of minor errors..

Should be easy to run on travis too - just install, then run it for all `*.md` files.

**Comment by matq007** [comment]
This is the tool I'll test on `nfcore/rnafusion` [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli)

**Comment by ewels** [comment]
My OCD is going to love this 🤓 

Can we run this on GitHub issue / PR comments as well please?? 😆

**Comment by matq007** [comment]
This was quite easy actually:
```yaml
# .travis.yml
install:
  # Install markdownlint-cli
  - sudo apt-get install npm && npm install -g markdownlint-cli
script:
- markdownlint ${TRAVIS_BUILD_DIR}/docs -c ${TRAVIS_BUILD_DIR}/conf/markdown-lint.yaml
```
and
```yaml
# markdown-lint.yaml
# Markdownlint configuration file
default: true,
line-length: false
```
Tested on `nfcore/rnafusion`: https://travis-ci.com/nf-core/rnafusion/jobs/172479363
