### ISSUE TITLE
Manual include or exclude specific files in template

### ISSUE THREAD

**Issue by adamrtalbot** [nf-core/tools#3088]
We should consider the ability to include or exclude specific files via the `.nf-core.yml` here. Not clear how we should do this yet but it could be a specific key for the `.nf-core.yml`:

```yaml
exclude:
  - .github/workflows/fix-linting.yml
  - .github/workflows/clean-up.yml
include:
  - .github/workflows/ci.yml
```

This would override the broad categories by the wizard. It could be bypassed when using the TUI for now, consider it an advanced feature.

_Originally posted by @adamrtalbot in https://github.com/nf-core/tools/pull/3084#discussion_r1697227173_
