### ISSUE TITLE
Add args section in meta.yml

### ISSUE THREAD

**Issue by arnaudbore** [nf-core/tools#3444]
### Description of feature

As discussed in the [slack thread](https://nfcore.slack.com/archives/CE5LG7WMB/p1738687919687259)

In @jfy133 words: 
```
We need a new section for listing each args (2, 3, 4) with the sole(?) metadata
for each one is simply the tool of the pipe it is effecting.
```

In @mirpedrol words:
```
We want an extra section in the meta.yml to describe the ext.args values.
At the level of tools , inputs and outputs.
```

It would look like this:

```
tools:
  - "bcftools":
      description: "..."
      homepage: ...
      args_id: "$args"
      identifier: biotools:bcftools
  - "bcftools plugin setGT":
      description: "..."
      homepage: ...
      args_id: "$args2"
      identifier: biotools:bcftools
args:
  - args:
      description: ""
  - args2:
      description: ""
input:
  - - meta:
        ...
    - vcf:
        ...
```
