### ISSUE TITLE
Comments after the input directive in the main.nf yields a false positive in the linter

### ISSUE THREAD

**Issue by nh13** [nf-core/tools#3457]
### Description of the bug

In https://github.com/nf-core/modules/pull/7480 the [linter complains](https://github.com/nf-core/modules/actions/runs/13316640975/job/37192399642#step:10:72):

> Module meta.yml does not match main.nf. Inputs should contain: [['meta', 'sample_sheet', 'fastq_readstructure_pairs'], ['to', '>]']] Run nf-core modules lint --fix to update the meta.yml file.

I've copied the meta.yaml and main.nf for debugging.  If I remove the comments after the input directive in the main.nf the linter doesn't complain:

<details>
<summary>diff of main.nf without comments</summary>

```console
diff --git a/modules/nf-core/fqtk/main.nf b/modules/nf-core/fqtk/main.nf
index 2f9637f3b..f955302af 100644
--- a/modules/nf-core/fqtk/main.nf
+++ b/modules/nf-core/fqtk/main.nf
@@ -9,8 +9,6 @@ process FQTK {
 
     input:
     tuple val(meta), path(sample_sheet), val(fastq_readstructure_pairs)
-    // fastq_readstructure_pairs example:
-    // [[<fastq name: string>, <read structure: string>, <path to fastqs: path>], [example_R1.fastq.gz, 150T, ./work/98/30bc..78y/fastqs/]]
 
     output:
     // Demultiplexed file name changes depending on the arg '--output-types'
```

</details>

<details>

<summary>meta.yaml</summary>

```yaml
name: "fqtk"
description: Demultiplex fastq files
keywords:
  - demultiplex
  - fastq
  - rust
tools:
  - "fqtk":
      description: "A toolkit for working with FASTQ files, written in Rust."
      homepage: "https://github.com/fulcrumgenomics/fqtk"
      documentation: "https://github.com/fulcrumgenomics/fqtk"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - sample_sheet:
        type: file
        description: Tsv file, with two columns sample_id and barcode
        pattern: "*.{tsv}"
    - fastq_readstructure_pairs:
        type: map
        description: List of lists i.e. [[<fastq file name>, <read structure>, <absolute
          path to fastq directory>],...]
output:
  - sample_fastq:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - output/*.fq.gz:
          type: file
          description: Demultiplexed per-sample FASTQ files
          pattern: "output/*R*.fastq.gz"
  - metrics:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - output/demux-metrics.txt:
          type: file
          description: |
            Demultiplexing summary stats; sample_id, barcode templates, frac_templates, ratio_to_mean, ratio_to_best
          pattern: "output/demux-metrics.txt"
  - most_frequent_unmatched:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - output/unmatched*.fq.gz:
          type: file
          description: |
            File containing unmatched fastq records
          pattern: "output/unmatched*.fq.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@nh13"
  - "@sam-white04"
maintainers:
  - "@nh13"
  - "@sam-white04"

```

</details>

<details>

<summary>main.nf</summary>

```nextflow
process FQTK {
    tag "$meta.id"
    label 'process_high'

    conda "${moduleDir}/environment.yml"
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/fqtk:0.3.1--ha6fb395_2' :
        'biocontainers/fqtk:0.3.1--ha6fb395_2' }"

    input:
    tuple val(meta), path(sample_sheet), val(fastq_readstructure_pairs)
    // fastq_readstructure_pairs example:
    // [[<fastq name: string>, <read structure: string>, <path to fastqs: path>], [example_R1.fastq.gz, 150T, ./work/98/30bc..78y/fastqs/]]

    output:
    // Demultiplexed file name changes depending on the arg '--output-types'
    tuple val(meta), path('output/*.fq.gz')                         , emit: sample_fastq
    tuple val(meta), path('output/demux-metrics.txt')               , emit: metrics
    tuple val(meta), path('output/unmatched*.fq.gz')                , emit: most_frequent_unmatched
    path "versions.yml"                                             , emit: versions


    when:
    task.ext.when == null || task.ext.when

    script:
    def args = task.ext.args ?: ''
    def prefix = task.ext.prefix ?: "${meta.id}"
    // Join the absolute path from UNTAR.out.untar to the fastq file names
    fastqs = fastq_readstructure_pairs.collect{it[2]/it[0]}.join(" ")
    // Create a list of read structures, Example: 8B 8B 150T
    read_structures = fastq_readstructure_pairs.collect{it[1]}.join(" ")

    """
    mkdir output
    fqtk \\
        demux \\
            --inputs ${fastqs} \\
            --read-structures ${read_structures} \\
            --output output/ \\
            --sample-metadata ${sample_sheet} \\
            ${args}
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        fqtk: \$(echo \$(fqtk --version 2>&1) | cut -d " " -f2)
    """
}

```
</details>

### Command used and terminal output

```console

```
