### ISSUE TITLE
Make generic Github Actions for marketplace

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#518]
As we're already adding GitHub actions from some of our tests, I think it'll be good to add more GitHub actions for some steps:
- [ ] Install Nextflow (version specific)
- [ ] Install nf-core tools (version specific) and run nf-core lint (version/release specific)
- [ ] Install and run markdownlint (maybe there's already one existing)
- [ ] Install and run YAML lint  (maybe there's already one existing)

**Comment by MaxUlysse** [comment]
- Markdownlint: https://github.com/marketplace?utf8=%E2%9C%93&type=actions&query=%22markdownlint%22+OR+%22markdown+lint%22
- YAMLlint: https://github.com/marketplace?utf8=%E2%9C%93&type=actions&query=%22YAMLlint%22+OR+%22YAML+Lint%22
- JSONLint:

**Comment by ewels** [comment]
You mean make new repos to put these actions on the GH marketplace?

**Comment by MaxUlysse** [comment]
Exactly

**Comment by ewels** [comment]
I wondered that at first. But then it seemed like quite a lot of work and I wasn’t sure what the benefit would be for us?

**Comment by MaxUlysse** [comment]
I looked into that as well, when we started to use Github Actions, and I had issues understanding the whole thing, but now, there are more repos with Actions and they are more detailed.

From what I see here:
https://github.com/gaurav-nelson/github-action-markdown-link-check
It's indeed a little work, but could be worth it.
I think the Install Nextlfow actions, could be done on the nextflow repo and the Install nf-core tools, run nf-core lint could be done in a repo in nf-core.

Also, regarding nf-core tools linting, I'm thinking that it's a tool that could be useful outside the nf-core community, if we could provide a config file to say which tests could be allowed to fail or not.
But that's another issue.

**Comment by ewels** [comment]
Yup, specifically this other issue: https://github.com/nf-core/tools/issues/389 😅

**Comment by MaxUlysse** [comment]
I knew we talked about that before.
So definitively, I think this actions could be good for the community

**Comment by mashehu** [comment]
If you need motivation to resolve this issue: https://githubhackathon.com 🙂

**Comment by ewels** [comment]
ooh, swag bags!

**Comment by maxibor** [comment]
@MaxUlysse I'm having a try at it

**Comment by MaxUlysse** [comment]
@nf-core/core Shall we create an nf-core/actions repo?

**Comment by ewels** [comment]
This is super cool @maxibor! Moving my thoughts here from Slack:

* Could the defaults be `null`, that is - get the latest version?
* It'd be nice to be able to use`--release` for the nf-core lint command
    * It looks like we've lost this in the current actions workflow, that needs fixing.. 
* Also the latest version needs a few ENV variables, I don't know how that would work?
    https://github.com/nf-core/tools/blob/28d8d0d943309f9a436a4517899046f967ebf4e3/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/.github/workflows/linting.yml#L56-L59

**Comment by ewels** [comment]
Also, I kind of like having separate jobs for the different types of linting currently:

<img src="https://user-images.githubusercontent.com/465550/87559151-36925d80-c6ba-11ea-9c42-85da9dbf08b4.png" width=300>

It makes it very simple to see from the PR interface what exactly is failing:

<img src="https://user-images.githubusercontent.com/465550/87559216-4b6ef100-c6ba-11ea-895a-8b37f806febf.png" width=300>

I guess that it's not possible to do this with a single action though. So my vote would be to strip out the markdown and yaml linting into their own actions if possible..

**Comment by maxibor** [comment]
All your comments have been addressed @ewels 
- By default, the latest version is installed
- The`release` mode is supported
- The ENV variables can be passed 
- The jobs are separated

The workflow looks like this now: 
```bash
name: nf-core linting
# This workflow is triggered on pushes and PRs to the repository.
# It runs the `nf-core lint` and markdown lint tests to ensure that the code meets the nf-core guidelines
on:
  push:
  pull_request:
  release:
    types: [published]


jobs:
  Markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Run Markdownlint
        run: markdownlint ${GITHUB_WORKSPACE} -c ${GITHUB_WORKSPACE}/.github/markdownlint.yml
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install yaml-lint
        run: npm install -g yaml-lint
      - name: Run yaml-lint
        run: yamllint $(find ${GITHUB_WORKSPACE} -type f -name "*.yml")
  nf-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: nf-core CI
      uses: maxibor/nf-core-gh-action@dev
      with:
          nextflow_version: '20.04.1'
          nfcore_version: '1.9'
          mode: ''
          GITHUB_COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_COMMIT: ${{ github.event.pull_request.head.sha }}
```

**Comment by ewels** [comment]
Love it! And I guess `mode` is for the release flag?

Can we have multiple actions in a single repo or is it one action per repo? Either way, yes I think that we should probably make a new repo for this / these..

Phil

**Comment by ewels** [comment]
Also, I guess that you can’t get at the`github.event` payload inside the action? As we could have a bunch of the standard logic wrapped in inside the action if so..

**Comment by maxibor** [comment]
Yes, `mode` if for the release flag. 
One repo = 1 action
GitHub action only accept ENV variable or arguments, so I don't think the `github.event` would work directly within the action.

**Comment by ewels** [comment]
Nice! Does it set up Python somewhere? I can't see that in the code (the `uses: actions/setup-python@v1` equivalent).

Can we get it to check out the code too? Would be nice if we could get down to a single step 🤓 

Comparison for my own curiosity...

_Current actions code_

```yaml
  nf-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nf-core
      - name: Run nf-core lint
        env:
          GITHUB_COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_COMMIT: ${{ github.event.pull_request.head.sha }}
        run: nf-core lint ${GITHUB_WORKSPACE}
```

_New actions code_

```yaml
  nf-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: nf-core CI
      uses: maxibor/nf-core-gh-action@dev
      with:
          mode: ${{ 'release' if (github.event_name == 'release') }}
          GITHUB_COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_COMMIT: ${{ github.event.pull_request.head.sha }}
```

Action would be a little easier to use if we change `mode` to `release` and make it boolean. Then we can just have `release: ${{ github.event_name == 'release' }}`. I'm not sure if my example code above would actually work.

Phil
